### ISSUE TITLE
Serve and build both broken

### ISSUE THREAD

**Issue by doublejosh** [superwolff/metalsmith-boilerplates#4]
I'm new to metalsmith so I can't offer any more details, but here the error...

`TypeError: Path must be a string. Received undefined`

**Comment by ismay** [comment]
It is quite difficult for me to figure out what went wrong with just the errormessage. Also, this repo isn’t actively maintained, so it’s possible that something broke.

I’d be open to adding you as a maintainer for it if you feel like it.

**Comment by ismay** [comment]
Let me know if you’d be up for that, I’d be happy to transfer ownership to you!
